// Per-state Healthcare POA overview content used by the /*-healthcare-poa
// landing pages. Kept intentionally factual and high-level; the authoritative
// rules live in each state's statutes (cited below) and may change. Templates
// generated by the product are reviewed by counsel independently of this file.

export interface StatePOAInfo {
  slug: string
  state: string
  docName: string // formal document name in that state
  statuteCitation: string
  statuteLabel: string
  execution: {
    witnesses: string
    notary: string
    whoCanBeAgent: string
  }
  quickFacts: string[]
  commonUses: string[]
}

export const STATE_POA_DATA: Record<string, StatePOAInfo> = {
  california: {
    slug: 'california',
    state: 'California',
    docName: 'Advance Health Care Directive',
    statuteCitation: 'Cal. Prob. Code §4670 et seq.',
    statuteLabel: "California's Health Care Decisions Law",
    execution: {
      witnesses:
        'Two adult witnesses, OR a notary public. Witnesses cannot be the agent, your health-care provider, or an employee of your provider.',
      notary:
        'Notarization is an alternative to witnesses. If you live in a skilled-nursing facility, a patient advocate must also witness.',
      whoCanBeAgent:
        'Any competent adult who is not your health-care provider or an employee of your provider (unless they are a relative).',
    },
    quickFacts: [
      'California combines your health-care proxy and living-will instructions into a single document called an Advance Health Care Directive.',
      'You can name a primary agent plus up to two alternates.',
      'The directive becomes effective only when a physician determines you cannot make your own health-care decisions.',
      'You can revoke or replace it at any time while you have capacity.',
    ],
    commonUses: [
      'Authorizing an agent to consent to or refuse treatment on your behalf.',
      'Documenting preferences about life-sustaining treatment, CPR, and artificial nutrition.',
      'Naming a preferred primary physician.',
      'Specifying anatomical-gift (organ-donation) wishes.',
    ],
  },
  texas: {
    slug: 'texas',
    state: 'Texas',
    docName: 'Medical Power of Attorney',
    statuteCitation: 'Tex. Health & Safety Code §166.151 et seq.',
    statuteLabel: "the Texas Advance Directives Act",
    execution: {
      witnesses:
        'Two adult witnesses, OR notarization. At least one witness cannot be related to you, entitled to any part of your estate, your attending physician, or an employee of your health-care facility.',
      notary:
        'Notarization is a valid alternative to two witnesses.',
      whoCanBeAgent:
        'Any competent adult. Your attending physician and their employees cannot serve unless they are also a relative.',
    },
    quickFacts: [
      'Texas calls the document a Medical Power of Attorney. The Directive to Physicians (a.k.a. living will) is a separate form.',
      'Authority activates only after your attending physician certifies in writing that you lack capacity.',
      'You can revoke at any time — orally, in writing, or by executing a new one.',
      'Your agent must follow your written instructions if they are clear; otherwise they must act in your best interest.',
    ],
    commonUses: [
      'Designating who can consent to medical treatment when you cannot.',
      'Spelling out preferences about life-sustaining care, ventilation, and artificial nutrition.',
      'Providing clear instructions for end-of-life decisions in Texas hospitals.',
    ],
  },
  florida: {
    slug: 'florida',
    state: 'Florida',
    docName: 'Designation of Health Care Surrogate',
    statuteCitation: 'Fla. Stat. §765.202',
    statuteLabel: "Florida's Health Care Advance Directives law",
    execution: {
      witnesses:
        'Two adult witnesses. One cannot be your spouse or a blood relative.',
      notary:
        'Notarization is not required for the designation itself, though some hospitals appreciate it.',
      whoCanBeAgent:
        'Any competent adult. The person you designate cannot serve as a witness on the same document.',
    },
    quickFacts: [
      'Florida calls the agent your "surrogate."',
      'You can make the surrogate\'s authority effective immediately or only upon your incapacity — Florida allows both.',
      'A separate Living Will form can be used to document end-of-life preferences.',
      'The designation can be revoked by written notice, oral statement, or execution of a new one.',
    ],
    commonUses: [
      'Authorizing a surrogate to consent to or refuse treatment on your behalf.',
      'Coordinating care decisions for aging parents in Florida.',
      'Giving the surrogate authority to access your medical records (HIPAA).',
    ],
  },
  'new-york': {
    slug: 'new-york',
    state: 'New York',
    docName: 'Health Care Proxy',
    statuteCitation: 'N.Y. Public Health Law §2981',
    statuteLabel: "New York's Health Care Proxy Law",
    execution: {
      witnesses:
        'Two adult witnesses. Your agent cannot serve as a witness.',
      notary:
        'Notarization is not required in New York.',
      whoCanBeAgent:
        'Any competent adult (18+). The operator, administrator, or employee of a hospital or facility where you are a patient cannot serve unless they are a relative.',
    },
    quickFacts: [
      'New York uses the term "Health Care Proxy." Living-will instructions can be attached or executed separately.',
      'The proxy becomes effective only when a physician determines you lack capacity.',
      'Special rules apply to decisions about artificial nutrition and hydration — you must give explicit instructions for your agent to withhold them.',
      'You can revoke at any time, including verbally.',
    ],
    commonUses: [
      'Naming a loved one to make medical decisions during emergencies.',
      'Ensuring New York hospitals honor your preferences quickly without court involvement.',
      'Pairing the proxy with a MOLST form for serious illness planning.',
    ],
  },
  illinois: {
    slug: 'illinois',
    state: 'Illinois',
    docName: 'Power of Attorney for Health Care',
    statuteCitation: '755 ILCS 45/4-1 et seq.',
    statuteLabel: "the Illinois Power of Attorney Act",
    execution: {
      witnesses:
        'One adult witness (18+). The witness cannot be your agent, your attending physician, or an employee of your physician or facility.',
      notary:
        'Notarization is not required. Only one witness is required in Illinois.',
      whoCanBeAgent:
        'Any competent adult other than your attending physician (or a physician providing care at the time).',
    },
    quickFacts: [
      'Illinois has a statutory short form that, when used, is presumed valid — our template is based on that form.',
      'Authority is effective immediately upon signing unless you specify otherwise, but your agent can only act if you are unable to decide for yourself.',
      'Only one witness is required, which streamlines execution compared with most states.',
      'You can revoke orally, in writing, or by physical destruction.',
    ],
    commonUses: [
      'Empowering an agent to access medical records and speak with doctors on your behalf.',
      'Documenting end-of-life and resuscitation preferences.',
      'Avoiding guardianship proceedings if you become incapacitated.',
    ],
  },
}
